# Generated by Django 4.2.3 on 2023-07-31 03:14

import app_gallery.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=50, unique=True, verbose_name='Etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app_gallery.models.picture_file_path)),
                ('thumbnail', models.ImageField(upload_to=app_gallery.models.thumbnail_file_path)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PictureHashtagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_relations', to='app_gallery.hashtag')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_relations', to='app_gallery.picture')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='pictures', through='app_gallery.PictureHashtagRelation', to='app_gallery.hashtag'),
        ),
    ]
