# Generated by Django 4.2.3 on 2023-08-04 03:15

import app_gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=app_gallery.models.thumbnail_file_path),
        ),
    ]
