# Generated by Django 4.2.3 on 2023-08-04 03:17

import app_gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gallery', '0002_alter_hashtag_hashtag_alter_picture_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=app_gallery.models.thumbnail_file_path),
        ),
    ]
